services:
  - type: web
    name: lms-rembot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: DEFAULT_SITE
        value: lms.kluniversity.in
